import { Slide } from "./types";
import slide1 from "./assets/slide1.jpeg";
import slide2 from "./assets/slide2.jpg";
import slide3 from "./assets/slide3.png";
import slide4 from "./assets/slide4.png";
import slide5 from "./assets/slide5.png";
import slide6 from "./assets/slide6.png";
import slide7 from "./assets/slide7.png";
import slide8 from "./assets/slide8.jpeg";
import slide9 from "./assets/slide9.jpg";
import slide10 from "./assets/slide10.webp";
import slide11 from "./assets/slide11.jpg";
import slide12 from "./assets/slide12.webp";
import slide13 from "./assets/slide13.webp";
import slide14 from "./assets/slide14.png";
import slide15 from "./assets/slide15.png";
import slide16 from "./assets/slide16.jpg";
import slide17 from "./assets/slide17.png";
import slide18 from "./assets/slide18.png";
import slide19 from "./assets/slide19.jpg";
// import slide20 from "./assets/slide20.png";

export const slides: Slide[] = [
  // Question 1
  {
    id: 1,
    question: "Legitimate Claim to Privacy?",
    title: "Understanding the Privacy Dilemma",
    points: [
      "Facebook users voluntarily share personal information",
      "Posting photos, location, opinions, and life events",
      "Raises the question: If we share it, do we still own it?",
      "Facebook argues social norms have changed",
    ],
    funLine:
      "In 2007 Facebook introduced the Beacon program, which was designed to broadcast users’ activities on participating websites to their friends.",
    image: slide1,
    author: "Keyur Puri",
    timestamp: "1h",
    likes: 124,
    comments: 45,
    shares: 12,
  },
  {
    id: 2,
    question: "Legitimate Claim to Privacy?",
    title: "Legitimate Claim to Privacy - YES",
    points: [
      "Users share content for social interaction, not commercial exploitation",
      "Sharing ≠ consent for data mining and resale",
      "Expectation of contextual privacy (friends vs advertisers)",
      "Ownership of identity does not disappear online",
    ],
    funLine:
      "Class-action suits followed and Beacon program was terminated in 2009, and Fb paid $9.5 million to settle the law suits",
    image: slide2,
    author: "Keyur Puri",
    timestamp: "2h",
    likes: 256,
    comments: 89,
    shares: 44,
  },
  {
    id: 3,
    question: "Legitimate Claim to Privacy?",
    title: "Facebook’s Business Model",
    points: [
      "Facebook’s core revenue = targeted advertising",
      "User data = product sold to advertisers",
      "More sharing → more data → higher ad value",
      "Unlike TV ads, Facebook knows who you are",
    ],
    funLine:
      "The very foundation of Facebook’s business model is to sell the personal private information of its users to advertisers",
    image: slide3,
    author: "Keyur Puri",
    timestamp: "3h",
    likes: 412,
    comments: 112,
    shares: 98,
  },
  {
    id: 4,
    question: "Legitimate Claim to Privacy?",
    title: "Ethical Perspective",
    points: [
      "Informed consent is often missing; policies are complex",
      "Users unaware of Facial Recognition, Sponsored Stories",
      "App data sharing is often opaque",
      "Ethically: Posting does NOT cancel privacy rights",
    ],
    image: slide4,
    author: "Keyur Puri",
    timestamp: "4h",
    likes: 331,
    comments: 67,
    shares: 23,
  },
  {
    id: 5,
    question: "Conclusion",
    title: "Conclusion: Privacy is Control",
    points: [
      "Yes, users have a legitimate privacy claim",
      "Voluntary sharing does not equal unlimited access",
      "Privacy is about control, not secrecy",
      "Facebook’s practices often exceed user expectations",
    ],
    image: slide5,
    author: "Keyur Puri",
    timestamp: "5h",
    likes: 892,
    comments: 234,
    shares: 156,
  },
  // Question 2
  {
    id: 6,
    question: "Privacy Controls?",
    title: "What Are Facebook Privacy Controls?",
    points: [
      "Limit audience (Friends, Public, Custom)",
      "Control tagging and facial recognition",
      "Manage app permissions & ad preferences",
      "Disappearing messages (Theory: Users are in control)",
    ],
    funLine:
      "In 2011, Facebook enrolled all Facebook subscribers into its facial recognition program without asking anyone.",
    image: slide6,
    author: "Saras Karanjit",
    timestamp: "6h",
    likes: 120,
    comments: 12,
    shares: 5,
  },
  {
    id: 7,
    question: "Privacy Controls?",
    title: "How Privacy Controls HELP",
    points: [
      "Reducing public exposure and unwanted tagging",
      "Restricting third-party apps",
      "Managing audience visibility (Locked Profile concept)",
      "Example: Stop strangers from seeing your photos",
    ],
    image: slide7,
    author: "Saras Karanjit",
    timestamp: "7h",
    likes: 450,
    comments: 56,
    shares: 21,
  },
  {
    id: 8,
    question: "Privacy Controls?",
    title: "Why Privacy Controls Are INEFFECTIVE",
    points: [
      "Over 170+ settings → confusing complexity",
      "Default setting = 'Share more'",
      "Frequent policy and interface changes",
      "Reality: Most users click 'Accept' and move on",
    ],
    funLine:
      "In 2021, Facebook finally terminated the facial recognition program after years of privacy concerns about it.",
    image: slide8,
    author: "Saras Karanjit",
    timestamp: "8h",
    likes: 720,
    comments: 150,
    shares: 88,
  },
  {
    id: 9,
    question: "Privacy Controls?",
    title: "Structural Weaknesses",
    points: [
      "Facebook still collects metadata (Time & frequency, Device, Location, Interaction)",
      "Scroll patterns and pauses",
      "Every click is recorded as an event",
      "Controls manage visibility, NOT data collection",
    ],
    image: slide9,
    author: "Saras Karanjit",
    timestamp: "9h",
    likes: 310,
    comments: 44,
    shares: 19,
  },
  {
    id: 10,
    question: "Conclusion",
    title: "Conclusion: The Illusion of Control",
    points: [
      "Controls provide surface-level privacy",
      "Ineffective against data mining and profiling",
      "Surveillance goes beyond Fb app (Meta quest, Meta glasses)",
      "Should have read the Terms and Conditions!",
    ],
    image: slide10,
    author: "Saras Karanjit",
    timestamp: "10h",
    likes: 540,
    comments: 90,
    shares: 70,
  },
  // Question 3
  {
    id: 11,
    question: "Google Data Ecosystem",
    title: "The Google Data Ecosystem",
    points: [
      "Services: Gmail, Search, YouTube, Maps",
      "Google processes over 8.5 billion searches per day",
      "Google Maps can infer your routines (home, office, gym) even if you never explicitly save them.",
      "Android collects background activity data, such as app usage patterns, even when apps are not actively open.",
    ],
    image: slide11,
    author: "Search Master",
    timestamp: "11h",
    likes: 98,
    comments: 5,
    shares: 2,
  },
  {
    id: 12,
    question: "Google Data Ecosystem",
    title: "Why Google Combines Data",
    points: [
      "Improve personalization and user experience",
      "Serve highly targeted ads (Revenue driver)",
      "Data becomes exponentially more valuable when combined",
      "One login = one digital identity",
    ],
    image: slide12,
    author: "Ad Strategist",
    timestamp: "12h",
    likes: 150,
    comments: 15,
    shares: 10,
  },
  {
    id: 13,
    question: "Google Data Ecosystem",
    title: "Privacy Implications",
    points: [
      "Reveals interests, location, health concerns",
      "Location patterns are nearly impossible to anonymize—four location points can uniquely identify 95% of people.",
      "Advertisers don’t buy data, they buy predictions",
      "Future predictions of buying behavior",
    ],
    funLine: "Google: We know you better than you know yourself.",
    image: slide13,
    author: "Cyber Watch",
    timestamp: "13h",
    likes: 1200,
    comments: 340,
    shares: 210,
  },
  {
    id: 14,
    question: "Google Data Ecosystem",
    title: "Ethical & Social Concerns",
    points: [
      "Users unaware of full data linkage depth",
      "No real opt-out without losing essential services",
      "Most users never read privacy policies",
      "Consent is often bundled, forcing users to accept tracking to access essential services like email or maps.",
    ],
    image: slide14,
    author: "Sociologist",
    timestamp: "14h",
    likes: 430,
    comments: 65,
    shares: 33,
  },
  {
    id: 15,
    question: "Conclusion",
    title: "Conclusion: Convenience vs Autonomy",
    points: [
      "Data combination amplifies privacy risks",
      "Individual data points become powerful when merged",
      "Convenience comes at the cost of autonomy",
      "Google users trade privacy for free services",
    ],
    funLine: "Is personalization worth permanent traceability?",
    image: slide15,
    author: "Tech Ethics",
    timestamp: "15h",
    likes: 990,
    comments: 120,
    shares: 88,
  },
  // Question 4
  {
    id: 16,
    question: "Google Street View",
    title: "What Is Google Street View?",
    points: [
      "Captures images of streets, houses, neighborhoods",
      "Photos taken without individual consent",
      "Publicly accessible worldwide",
      "Your house is online — whether you like it or not",
    ],
    image: slide16,
    author: "Map Explorer",
    timestamp: "16h",
    likes: 220,
    comments: 40,
    shares: 15,
  },
  {
    id: 17,
    question: "Google Street View",
    title: "Argument: NOT a Breach",
    points: [
      "Images taken from public roads",
      "No expectation of privacy in public space",
      "Faces and license plates are blurred",
      "Legal justification: Public domain observation",
    ],
    image: slide17,
    author: "Legal Scholar",
    timestamp: "17h",
    likes: 180,
    comments: 90,
    shares: 12,
  },
  {
    id: 18,
    question: "Google Street View",
    title: "Argument: IS a Breach",
    points: [
      "Homes linked to exact locations",
      "Reveals personal lifestyle details and assets",
      "Can be misused for stalking or profiling",
      "No explicit consent obtained for digital permanence",
    ],
    image: slide18,
    author: "Privacy Advocate",
    timestamp: "18h",
    likes: 670,
    comments: 110,
    shares: 45,
  },
  {
    id: 19,
    question: "Google Street View",
    title: "Personal Reflection",
    points: [
      "Looking up one's address creates discomfort",
      "Loss of control over personal physical space",
      "Highlights surveillance normalization",
      "Just because it's legal doesn't mean it feels right",
    ],
    funLine: "My home, my castle... now on everyone's screen.",
    image: slide19,
    author: "Homeowner",
    timestamp: "19h",
    likes: 440,
    comments: 88,
    shares: 30,
  },
  {
    id: 20,
    question: "Final Conclusion",
    title: "The Negotiated State of Privacy",
    points: [
      "Street View sits in a legal/ethical grey area",
      "Technology has outpaced privacy norms",
      "Privacy today is negotiated, not guaranteed",
      "Overall takeaway: Constant vigilance required",
    ],
    image: "https://picsum.photos/seed/street5/800/600",
    author: "The Futurist",
    timestamp: "20h",
    likes: 1500,
    comments: 450,
    shares: 320,
  },
];
